apiVersion: v1
kind: Service 
metadata: 
  name: nginx
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: nginx.eks.maferreira94.shop
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http